### ISSUE TITLE
Vaadin Lumo package?

### ISSUE THREAD

**Issue by lkraav** [web-padawan/aybolit#8]
Any plans? Or what would be the alternative integration strategy, if we like Lumo's system in general.

**Comment by web-padawan** [comment]
Thanks for the issue. I don't have any plans to integrate Lumo at this point due to the reasons:

1. Aybolit is my personal pet-project, not associated with Vaadin. I'm working on it in my free time only, and I'm not getting paid for it. And I would prefer to keep MIT license here.

2. Lumo, in its current shape, introduces some complexity which I would like to avoid - especially, it relies on extra wrappers in certain components, selectors like `:host::before` for alignment etc.

3. Lumo still has to support IE11, and in Aybolit I would like to feel a breath of fresh air and drop the support for this [compatibility solution](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732) in order to gain more power and flexibility.

So the only integration strategy I can recommend would be extending "white label" components and tweaking the CSS manually to make them look visually similar to Lumo, using same colors etc.

**Comment by lkraav** [comment]
If we look to use Vaadin components, I think we will be having Lumo in active play regardless. For now.

It seems like an unfeasible amount of work to recreate an optimized "Aybolumo" in Aybolit (kill `:host::before` wrappers, etc), then also somehow get Vaadin components re-styled for "Aybolumo".

I'm thinking if starting with Vaadin and Lumo today, while writing our own components in Aybolit structure, we simply migrate and evolve towards "better" with the upstream over time.

Are there any significant flaws in this thinking model?

**Comment by web-padawan** [comment]
Yes, I think that's a good idea. Vaadin components are a complete set, while Aybolit is personal project and experiment, so it's unlikely that I will be able to cover all the components any time soon.

**Comment by lkraav** [comment]
> So it's unlikely that I will be able to cover all the components any time soon.

We'd be motivated to consistently help along. I just can't imagine off the top of my head what the process of merging upstream changes would be, is there any merge automation available at all, or all changes need to be cherry-picked (aka unsustainable).
